# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
 branches:
    include:
    - master
    - release/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- name: Major
  value: '3'
- name: Minor
  value: '6'
- name: Patch
  value: $[counter(variables['BuildID'], 0)]
- name: SemanticVersion
  value: $(Major).$(Minor).$(Patch)
- name: SemanticVersionPack
  ${{ if and(  startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), ne( variables['Build.Reason'], 'PullRequest' )  ) }}:
    value: $(Major).$(Minor).$(Patch)
  ${{ if and(  startsWith(variables['Build.SourceBranch'], 'refs/heads/master'),  ne( variables['Build.Reason'], 'PullRequest' )  ) }}:
    value: $(Major).$(Minor).$(Patch)-prerelease
  ${{ if eq( variables['Build.Reason'], 'PullRequest' )  }}:
    value: $(Major).$(Minor).$(Patch)-alpha
- name: PublishPackage
  ${{ if and(  startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), ne( variables['Build.Reason'], 'PullRequest' )  ) }}:
    value: 'true'
  ${{ if and(  startsWith(variables['Build.SourceBranch'], 'refs/heads/master'),  ne( variables['Build.Reason'], 'PullRequest' )  ) }}:
    value: 'true'
  ${{ if  eq( variables['Build.Reason'], 'PullRequest' )  }}:
    value: 'false'

steps:
- script: echo $(SemanticVersion)
- script: echo $(SemanticVersionPack)
- script: echo $(PublishPackage) 

#Set the assembly file and version numbers to be the build number
- template: set-semantic-version.yaml
  parameters:
    SemanticVersion: "$(SemanticVersion)"
    ProjectFile: "CA.Blocks.DataAccess"
    
- template: set-semantic-version.yaml
  parameters:
    SemanticVersion: "$(SemanticVersion)"
    ProjectFile: "CA.Blocks.DataAccess.Extensions.Translators.Json"

- template: set-semantic-version.yaml
  parameters:
    SemanticVersion: "$(SemanticVersion)"
    ProjectFile: "CA.Blocks.DataAccess.Extensions.Config.Json"

- template: set-semantic-version.yaml
  parameters:
    SemanticVersion: "$(SemanticVersion)"
    ProjectFile: "CA.Blocks.DataAccess.Extensions.Translators.NUlid"

- template: set-semantic-version.yaml
  parameters:
    SemanticVersion: "$(SemanticVersion)"
    ProjectFile: "CA.Blocks.DataAccess.Model"

- template: set-semantic-version.yaml
  parameters:
    SemanticVersion: "$(SemanticVersion)"
    ProjectFile: "CA.Blocks.SqliteDataAccess"
        
- template: set-semantic-version.yaml
  parameters:
    SemanticVersion: "$(SemanticVersion)"
    ProjectFile: "CA.Blocks.SQLServerDataAccess"

- template: set-semantic-version.yaml
  parameters:
    SemanticVersion: "$(SemanticVersion)"
    ProjectFile: "CA.Blocks.OdbcDataAccess"

# - task: NuGetToolInstaller@1
#   displayName: 'NuGetToolInstaller' 
  
- task: UseDotNet@2
  displayName: 'Install .NET 9 SDK'
  continueOnError: false
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    
- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  continueOnError: false
  inputs:
        command: restore

# WE have a dependency on SQL so only run the DataAccessUnitTests and SqliteDataAccessUnitTests tests which can run in memory

- task: DotNetCoreCLI@2
  displayName: 'Build and Test'
  continueOnError: false
  inputs:
       command: test
       projects: |
            **/*.csproj
            !**/*SQLServerDataAccessUnitTests.csproj
            !**/*MySQLDataAccessUnitTests.csproj
            !**/*OdbcDataAccessUnitTests.csproj
       arguments: >
          --configuration $(BuildConfiguration)
          --collect "Code coverage"
          /p:ExcludeByAttribute=Obsolete

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj;!**/*Tests.csproj;!**/*Benchmarks.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byEnvVar
    versionEnvVar : SemanticVersionPack
    includesymbols: true

- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

# - task: NuGetAuthenticate@1
#   displayName: 'NuGetAuthenticate' 

- task: DotNetCoreCLI@2
  displayName: 'dotnet nuget push'
  condition: "eq('true', variables['PublishPackage'])"
  inputs:
    command: custom
    custom: nuget
    arguments: 'push "$(Build.ArtifactStagingDirectory)/**/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k $(NugetApiKey)'
