# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '2'
  Minor: '1'
  Patch : $[counter(variables['BuildID'], 0)]

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# WE have a dependency on SQL so only run the SQLLite tests
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
        **\CA.Blocks.SQLLiteDataAccessUnitTests.dll
        !**\obj\**
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: True # Optional

# Publish build artifacts
# Publish build artifacts to Azure Pipelines or a Windows file share
# - task: PublishBuildArtifacts@1
#  inputs:
#    pathtoPublish: '$(System.DefaultWorkingDirectory)/CA.Blocks.DataAccess/CA.Blocks.DataAccess/bin/Release/*.nupkg' 
#    artifactName: CA.Blocks.DataAccess 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
    #fileCopyOptions: #Optional

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj;!**/*Tests.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byPrereleaseNumber
    majorVersion : $(Major)
    minorVersion : $(Minor)
    patchVersion : $(Patch)
    includeReferencedProjects: true

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'CA_Blocks_Feed'
    allowPackageConflicts: true


- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'