# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '2'
  Minor: '2'
  Patch : $[counter(variables['BuildID'], 0)]
  SemanticVerion : $(Major).$(Minor).$(Patch)

steps:
- script: echo $(SemanticVerion)


#Set the assembly file and version numbers to be the build number
 - task: PowerShell@2
  inputs:
    targetType: 'inline'
    workingDirectory: '$(Build.SourcesDirectory)\CA.Blocks.DataAccess\'
    script: '((Get-Content -path CA.Blocks.DataAccess.csproj -Raw) -replace "987.654.3210","$(SemanticVerion)") | Set-Content -Path CA.Blocks.DataAccess.csproj'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    workingDirectory: '$(Build.SourcesDirectory)\CA.Blocks.DataAccess.Model\'
    script: '((Get-Content -path CA.Blocks.DataAccess.Model.csproj -Raw) -replace "987.654.3210","$(SemanticVerion)") | Set-Content -Path CA.Blocks.DataAccess.Model.csproj'

 - task: PowerShell@2
  inputs:
    targetType: 'inline'
    workingDirectory: '$(Build.SourcesDirectory)\CA.Blocks.SQLLiteDataAccess\'
    script: '((Get-Content -path CA.Blocks.SQLLiteDataAccess.csproj -Raw) -replace "987.654.3210","$(SemanticVerion)") | Set-Content -Path CA.Blocks.SQLLiteDataAccess.csproj'

 - task: PowerShell@2
  inputs:
    targetType: 'inline'
    workingDirectory: '$(Build.SourcesDirectory)\CA.Blocks.SQLServerDataAccess\'
    script: '((Get-Content -path CA.Blocks.SQLServerDataAccess.csproj -Raw) -replace "987.654.3210","$(SemanticVerion)") | Set-Content -Path CA.Blocks.SQLServerDataAccess.csproj'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# WE have a dependency on SQL so only run the SQLLite tests
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
        **\CA.Blocks.SQLLiteDataAccessUnitTests.dll
        !**\obj\**
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: True # Optional


- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj;!**/*Tests.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byEnvVar
    versionEnvVar : SemanticVerion

#- task: NuGetAuthenticate@0
#  displayName: 'NuGet Authenticate'

#- task: NuGetCommand@2
#  displayName: 'NuGet push'
#  inputs:
#    command: push
#    publishVstsFeed: 'CA_Blocks_Feed'
#    allowPackageConflicts: true


- task: PublishBuildArtifacts@1    
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'