<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>

	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <AssemblyVersion>987.654.3210.0</AssemblyVersion>
	  <FileVersion>987.654.3210.0</FileVersion>
	  <Version>987.654.3210</Version>
	  <RepositoryUrl>https://dev.azure.com/RavinEnterprises/CA.Blocks/_git/CA.Blocks.DataAccess</RepositoryUrl>

	  <Authors>Kevin Bosch</Authors>
	  <Company>Ravin Enterprises Limited</Company>
	  <Title>CA.Blocks.DataAccess.Extensions.Config.Json</Title>
	  <RepositoryType>git</RepositoryType>
	  <PackageProjectUrl>https://www.codeassociate.com/Blocks/DataAccess/</PackageProjectUrl>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageReleaseNotes>@RELEASE-NOTES.txt</PackageReleaseNotes>
	  <PackageTags>data;micro-orm;sql;ca.blocks;ado.net</PackageTags>
	  <IncludeSymbols>True</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CA.Blocks.DataAccess\CA.Blocks.DataAccess.csproj" />
  </ItemGroup>

	<ItemGroup>
		<None Include="..\CA.Blocks.DataAccess.Extensions.Config.Json\readme.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
