<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="Dapper" Version="2.1.66" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CA.Blocks.SQLServerDataAccess\CA.Blocks.SQLServerDataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Benchmarks\ReadVrsDapper\ReadDapper\" />
    <Folder Include="Benchmarks\ReadVrsDapper\ReadBlocks\" />
    <Folder Include="Benchmarks\Translator\DbColToType\" />
  </ItemGroup>

</Project>
