<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <AssemblyVersion>987.654.3210.0</AssemblyVersion>
	  <FileVersion>987.654.3210.0</FileVersion>
	  <Version>987.654.3210</Version>
	  <RepositoryUrl>https://dev.azure.com/RavinEnterprises/CA.Blocks/_git/CA.Blocks.DataAccess</RepositoryUrl>
	  <AssemblyName>CA.Blocks.SQLLiteDataAccess</AssemblyName>
	  <RootNamespace>CA.Blocks.SQLLiteDataAccess</RootNamespace>
	  <Authors>Kevin Bosch</Authors>
	  <Company>Ravin Enterprises Limited</Company>
	  <Title>CA.Blocks.SQLLiteDataAccess</Title>
	  <RepositoryType>git</RepositoryType>
	  <PackageProjectUrl>https://www.codeassociate.com/Blocks/DataAccess/</PackageProjectUrl>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageReadmeFile>readme.md</PackageReadmeFile>
	  <PackageTags>data;micro-orm;sql;ca.blocks;ado.net;sqlite</PackageTags>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>.\CA.Blocks.SQLLiteDataAccess.xml</DocumentationFile>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CA.Blocks.DataAccess.Model\CA.Blocks.DataAccess.Model.csproj" />
    <ProjectReference Include="..\CA.Blocks.DataAccess\CA.Blocks.DataAccess.csproj" />
  </ItemGroup>

</Project>
