<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <AssemblyVersion>987.654.3210.0</AssemblyVersion>
	  <FileVersion>987.654.3210.0</FileVersion>
	  <Version>987.654.3210</Version>
    <RepositoryUrl>https://github.com/CodeAssociate/CA.Blocks.DataAccess</RepositoryUrl>
	  <AssemblyName>CA.Blocks.SqliteDataAccess</AssemblyName>
	  <RootNamespace>CA.Blocks.SqliteDataAccess</RootNamespace>
	  <Authors>Kevin Bosch</Authors>
	  <Company>Ravin Enterprises Limited</Company>
	  <Title>CA.Blocks.SQLLiteDataAccess</Title>
	  <RepositoryType>git</RepositoryType>
	  <PackageProjectUrl>https://www.codeassociate.com/Blocks/DataAccess/</PackageProjectUrl>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <PackageReleaseNotes>@RELEASE-NOTES.txt</PackageReleaseNotes>
	  <PackageReadmeFile>readme.md</PackageReadmeFile>
	  <PackageTags>data;micro-orm;sql;ca.blocks;ado.net;sqlite</PackageTags>
	  <IncludeSymbols>True</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>.\CA.Blocks.SqliteDataAccess.xml</DocumentationFile>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\CA.Blocks.SqliteDataAccess\readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CA.Blocks.DataAccess.Model\CA.Blocks.DataAccess.Model.csproj" />
    <ProjectReference Include="..\CA.Blocks.DataAccess\CA.Blocks.DataAccess.csproj" />
  </ItemGroup>
	<ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	</ItemGroup>
	<ItemGroup>
	  <None Update="readme.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
