<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" Version="13.4.6" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CA.Blocks.DataAccess.Extensions.Translators.Json\CA.Blocks.DataAccess.Extensions.Translators.Json.csproj" />
    <ProjectReference Include="..\CA.Blocks.DataAccess.Extensions.Translators.NUlid\CA.Blocks.DataAccess.Extensions.Translators.NUlid.csproj" />
    <ProjectReference Include="..\CA.Blocks.DataAccessTestDataForUnitTests\CA.Blocks.DataAccessTestDataForUnitTests.csproj" />
    <ProjectReference Include="..\CA.Blocks.SQLServer.AppHost\CA.Blocks.SQLServer.AppHost.csproj" />
    <ProjectReference Include="..\CA.Blocks.SQLServerDataAccess\CA.Blocks.SQLServerDataAccess.csproj" />
  </ItemGroup>

</Project>
