<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>2.0.9</Version>
    <Authors>Kevin Bosch</Authors>
    <Company>Ravin Enterprises Limited</Company>
    <Description>Simple fast framework for accessing a SQL server database using ADO.NET from .NET core</Description>
    <Copyright>Copyright 2019</Copyright>
    <PackageTags>CA.CoreBlocks.DataAcess</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyVersion>2.0.8.0</AssemblyVersion>
    <FileVersion>2.0.8.0</FileVersion>
    <PackageId>CA.Blocks.SQLServerDataAccess</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CA.Blocks.DataAccess\CA.Blocks.DataAccess.csproj" />
  </ItemGroup>

</Project>
