<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyVersion>987.654.3210.0</AssemblyVersion>
    <FileVersion>987.654.3210.0</FileVersion>
    <Version>987.654.3210</Version>
    <Authors>Kevin Bosch</Authors>
    <Company>Ravin Enterprises Limited</Company>
    <Description>Simple fast framework for accessing a SQL server database using ADO.NET from .NET core</Description>
    <Copyright>Copyright 2019</Copyright>
    <PackageTags>CA.CoreBlocks.DataAcess</PackageTags>
    <PackageId>CA.Blocks.SQLServerDataAccess</PackageId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>C:\GitHub\CA.Blocks.DataAccess\CA.Blocks.SQLServerDataAccess\CA.Blocks.SQLServerDataAccess.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CA.Blocks.DataAccess\CA.Blocks.DataAccess.csproj" />
  </ItemGroup>

</Project>
