using System;
using System.Collections.Generic;
using System.Text;

namespace CA.Blocks.DataAccess.Generators
{
    public static class TranslatorEmitter
    {
        public static string Emit(TypeToGenerate type)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Data;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using CA.Blocks.DataAccess;");
            sb.AppendLine("using CA.Blocks.DataAccess.Translator.DbRowToObject.Interfaces;");
            sb.AppendLine("using CA.Blocks.DataAccess.Translator.DbRowToObject.Providers;");
            sb.AppendLine("using CA.Blocks.DataAccess.Translator.DbColToType.Interfaces;");
            sb.AppendLine("using CA.Blocks.DataAccess.Translator.DbColToType.Providers;");
            sb.AppendLine("using CA.Blocks.DataAccess.Translator.DbColToType.Exceptions;");
            sb.AppendLine();

            string ns = string.IsNullOrWhiteSpace(type.TargetNamespace) ? "CA.Blocks.DataAccess.Generated" : type.TargetNamespace;

            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Compile-time strongly-typed IDbRowTranslator for <see cref=\"{type.FullTypeName}\"/>.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    {type.Accessibility} sealed partial class {type.TranslatorClassName} : IDbRowTranslator<{type.FullTypeName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {type.TranslatorClassName} Instance = new {type.TranslatorClassName}();");
            sb.AppendLine();

            // Custom or resolved converter fields
            foreach (var prop in type.Properties)
            {
                if (prop.Kind == PropertyKind.CustomConverter && !string.IsNullOrWhiteSpace(prop.CustomConverterTypeName))
                {
                    string args = string.Join(", ", prop.CustomConverterArguments);
                    sb.AppendLine($"        private static readonly {prop.CustomConverterTypeName} _converter_{prop.PropertyName} = new {prop.CustomConverterTypeName}({args});");
                }
                else if (prop.Kind == PropertyKind.Object)
                {
                    sb.AppendLine($"        private static readonly Lazy<IDbColToTypeConverter> _converter_{prop.PropertyName} = new Lazy<IDbColToTypeConverter>(() => DefaultDbColToTypeProvider.DefaultInstance.Resolve(typeof({prop.PropertyTypeName})));");
                }
            }
            sb.AppendLine();

            // Struct for ordinals
            sb.AppendLine("        private struct ReaderOrdinals");
            sb.AppendLine("        {");
            foreach (var prop in type.Properties)
            {
                sb.AppendLine($"            public int {prop.PropertyName}Ordinal;");
            }
            sb.AppendLine();
            sb.AppendLine("            public void InitDefaults()");
            sb.AppendLine("            {");
            foreach (var prop in type.Properties)
            {
                sb.AppendLine($"                {prop.PropertyName}Ordinal = -1;");
            }
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Weak tables for caching
            sb.AppendLine("        private static readonly ConditionalWeakTable<IDataReader, StrongBox<ReaderOrdinals>> _readerCache = new ConditionalWeakTable<IDataReader, StrongBox<ReaderOrdinals>>();");
            sb.AppendLine("        private static readonly ConditionalWeakTable<DataTable, StrongBox<ReaderOrdinals>> _tableCache = new ConditionalWeakTable<DataTable, StrongBox<ReaderOrdinals>>();");
            sb.AppendLine();

            // Normalization method
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("        private static string NormalizeColName(string name)");
            sb.AppendLine("        {");
            if (type.MatchNamesWithUnderscores && type.MatchCaseInsensitive)
            {
                sb.AppendLine("            return name.ToLowerInvariant().Replace(\"_\", string.Empty);");
            }
            else if (type.MatchNamesWithUnderscores && !type.MatchCaseInsensitive)
            {
                sb.AppendLine("            return name.Replace(\"_\", string.Empty);");
            }
            else if (!type.MatchNamesWithUnderscores && type.MatchCaseInsensitive)
            {
                sb.AppendLine("            return name.ToLowerInvariant();");
            }
            else
            {
                sb.AppendLine("            return name;");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // ResolveReaderOrdinals
            sb.AppendLine("        private static StrongBox<ReaderOrdinals> ResolveReaderOrdinals(IDataReader dr)");
            sb.AppendLine("        {");
            sb.AppendLine("            var ords = new ReaderOrdinals();");
            sb.AppendLine("            ords.InitDefaults();");
            sb.AppendLine();
            sb.AppendLine("            for (int i = 0; i < dr.FieldCount; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                string rawName = dr.GetName(i);");
            sb.AppendLine("                if (string.IsNullOrEmpty(rawName)) continue;");
            sb.AppendLine("                string col = NormalizeColName(rawName);");
            sb.AppendLine();
            sb.AppendLine("                switch (col)");
            sb.AppendLine("                {");

            foreach (var prop in type.Properties)
            {
                string normCol = NormalizeString(prop.SourceColumnName, type.MatchNamesWithUnderscores, type.MatchCaseInsensitive);
                sb.AppendLine($"                    case \"{normCol}\":");
                sb.AppendLine($"                        ords.{prop.PropertyName}Ordinal = i;");
                sb.AppendLine("                        break;");
            }

            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine();

            if (type.ThrowIfColumnNotFound)
            {
                foreach (var prop in type.Properties)
                {
                    sb.AppendLine($"            if (ords.{prop.PropertyName}Ordinal < 0)");
                    sb.AppendLine($"                throw new ConverterColumnNotFoundException(\"The column '{prop.SourceColumnName}' was expected in the result set but not found\");");
                }
            }

            sb.AppendLine("            return new StrongBox<ReaderOrdinals>(ords);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ResolveTableOrdinals
            sb.AppendLine("        private static StrongBox<ReaderOrdinals> ResolveTableOrdinals(DataTable dt)");
            sb.AppendLine("        {");
            sb.AppendLine("            var ords = new ReaderOrdinals();");
            sb.AppendLine("            ords.InitDefaults();");
            sb.AppendLine();
            sb.AppendLine("            for (int i = 0; i < dt.Columns.Count; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                string rawName = dt.Columns[i].ColumnName;");
            sb.AppendLine("                if (string.IsNullOrEmpty(rawName)) continue;");
            sb.AppendLine("                string col = NormalizeColName(rawName);");
            sb.AppendLine();
            sb.AppendLine("                switch (col)");
            sb.AppendLine("                {");

            foreach (var prop in type.Properties)
            {
                string normCol = NormalizeString(prop.SourceColumnName, type.MatchNamesWithUnderscores, type.MatchCaseInsensitive);
                sb.AppendLine($"                    case \"{normCol}\":");
                sb.AppendLine($"                        ords.{prop.PropertyName}Ordinal = i;");
                sb.AppendLine("                        break;");
            }

            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine();

            if (type.ThrowIfColumnNotFound)
            {
                foreach (var prop in type.Properties)
                {
                    sb.AppendLine($"            if (ords.{prop.PropertyName}Ordinal < 0)");
                    sb.AppendLine($"                throw new ConverterColumnNotFoundException(\"The column '{prop.SourceColumnName}' was expected in the result set but not found\");");
                }
            }

            sb.AppendLine("            return new StrongBox<ReaderOrdinals>(ords);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Translate(IDataReader)
            sb.AppendLine($"        public {type.FullTypeName} Translate(IDataReader dr)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (dr == null || dr.IsClosed)");
            sb.AppendLine("            {");
            sb.AppendLine("                return default!;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            var box = _readerCache.GetValue(dr, ResolveReaderOrdinals);");
            sb.AppendLine("            ref readonly var ords = ref box.Value;");
            sb.AppendLine();

            foreach (var prop in type.Properties)
            {
                EmitDataReaderPropertyAssignment(sb, prop);
            }

            sb.AppendLine();
            if (type.Properties.Length == 0)
            {
                sb.AppendLine($"            var item = new {type.FullTypeName}();");
            }
            else
            {
                sb.AppendLine($"            var item = new {type.FullTypeName}");
                sb.AppendLine("            {");
                foreach (var prop in type.Properties)
                {
                    sb.AppendLine($"                {prop.PropertyName} = val_{prop.PropertyName},");
                }
                sb.AppendLine("            };");
            }
            sb.AppendLine();
            sb.AppendLine("            CustomTranslate(dr, item);");
            sb.AppendLine("            return item;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Translate(DataRow)
            sb.AppendLine($"        public {type.FullTypeName} Translate(DataRow dr)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (dr == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                return default!;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            var box = _tableCache.GetValue(dr.Table, ResolveTableOrdinals);");
            sb.AppendLine("            ref readonly var ords = ref box.Value;");
            sb.AppendLine();

            foreach (var prop in type.Properties)
            {
                EmitDataRowPropertyAssignment(sb, prop);
            }

            sb.AppendLine();
            if (type.Properties.Length == 0)
            {
                sb.AppendLine($"            var item = new {type.FullTypeName}();");
            }
            else
            {
                sb.AppendLine($"            var item = new {type.FullTypeName}");
                sb.AppendLine("            {");
                foreach (var prop in type.Properties)
                {
                    sb.AppendLine($"                {prop.PropertyName} = val_{prop.PropertyName},");
                }
                sb.AppendLine("            };");
            }
            sb.AppendLine();
            sb.AppendLine("            CustomTranslate(dr, item);");
            sb.AppendLine("            return item;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Translate(DataTable)
            sb.AppendLine($"        public IList<{type.FullTypeName}> Translate(DataTable dt)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (dt == null || dt.Rows.Count == 0)");
            sb.AppendLine("            {");
            sb.AppendLine($"                return new List<{type.FullTypeName}>(0);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine($"            var list = new List<{type.FullTypeName}>(dt.Rows.Count);");
            sb.AppendLine("            for (int i = 0; i < dt.Rows.Count; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                list.Add(Translate(dt.Rows[i]));");
            sb.AppendLine("            }");
            sb.AppendLine("            return list;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // CustomTranslate partial methods
            sb.AppendLine($"        partial void CustomTranslate(IDataReader dr, {type.FullTypeName} item);");
            sb.AppendLine($"        partial void CustomTranslate(DataRow dr, {type.FullTypeName} item);");
            sb.AppendLine();

            // Auto-registration
            if (type.AutoRegister)
            {
                string byNameArg = string.IsNullOrEmpty(type.ByName) ? string.Empty : $", \"{type.ByName}\"";
                sb.AppendLine("        [ModuleInitializer]");
                sb.AppendLine("        internal static void AutoRegister()");
                sb.AppendLine("        {");
                sb.AppendLine($"            DefaultDbRowTranslatorProvider.DefaultInstance.Add(Instance{byNameArg});");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string NormalizeString(string s, bool matchUnderscores, bool matchCaseInsensitive)
        {
            if (string.IsNullOrEmpty(s)) return string.Empty;
            string res = s;
            if (matchUnderscores)
                res = res.Replace("_", string.Empty);
            if (matchCaseInsensitive)
                res = res.ToLowerInvariant();
            return res;
        }

        private static void EmitDataReaderPropertyAssignment(StringBuilder sb, PropertyToGenerate prop)
        {
            if (prop.Kind == PropertyKind.String && !prop.PropertyTypeName.EndsWith("?"))
            {
                sb.AppendLine($"            {prop.PropertyTypeName} val_{prop.PropertyName} = string.Empty;");
            }
            else
            {
                sb.AppendLine($"            {prop.PropertyTypeName} val_{prop.PropertyName} = default!;");
            }

            sb.AppendLine($"            if (ords.{prop.PropertyName}Ordinal >= 0)");
            sb.AppendLine("            {");

            switch (prop.Kind)
            {
                case PropertyKind.String:
                    if (prop.PropertyTypeName.EndsWith("?"))
                    {
                        sb.AppendLine($"                val_{prop.PropertyName} = dr.AsString(ords.{prop.PropertyName}Ordinal);");
                    }
                    else
                    {
                        sb.AppendLine($"                val_{prop.PropertyName} = dr.AsString(ords.{prop.PropertyName}Ordinal) ?? string.Empty;");
                    }
                    break;
                case PropertyKind.Int32:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsInt(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableInt32:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullInt(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Int64:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsLong(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableInt64:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullLong(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Int16:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsShort(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableInt16:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullShort(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Byte:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsByte(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableByte:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullByte(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.SByte:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsSByte(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableSByte:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullSByte(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.UInt32:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsUInt(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableUInt32:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullUInt(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.UInt64:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsULong(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableUInt64:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullULong(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.UInt16:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsUShort(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableUInt16:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullUShort(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Boolean:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsBool(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableBoolean:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullBool(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.DateTime:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsDateTime(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableDateTime:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullDateTime(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.DateTimeOffset:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsDateTimeOffset(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableDateTimeOffset:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullDateTimeOffset(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Guid:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsGuid(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableGuid:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullGuid(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Decimal:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsDecimal(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableDecimal:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullDecimal(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Double:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsDouble(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableDouble:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullDouble(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Single:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsFloat(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableSingle:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullFloat(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.ByteArray:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsBinary(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.DateOnly:
                    sb.AppendLine("#if NET6_0_OR_GREATER");
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsDateOnly(ords.{prop.PropertyName}Ordinal);");
                    sb.AppendLine("#endif");
                    break;
                case PropertyKind.NullableDateOnly:
                    sb.AppendLine("#if NET6_0_OR_GREATER");
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullDateOnly(ords.{prop.PropertyName}Ordinal);");
                    sb.AppendLine("#endif");
                    break;
                case PropertyKind.TimeOnly:
                    sb.AppendLine("#if NET6_0_OR_GREATER");
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsTimeOnly(ords.{prop.PropertyName}Ordinal);");
                    sb.AppendLine("#endif");
                    break;
                case PropertyKind.NullableTimeOnly:
                    sb.AppendLine("#if NET6_0_OR_GREATER");
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullTimeOnly(ords.{prop.PropertyName}Ordinal);");
                    sb.AppendLine("#endif");
                    break;
                case PropertyKind.Enum:
                    sb.AppendLine($"                var enumStr_{prop.PropertyName} = dr.AsToString(ords.{prop.PropertyName}Ordinal);");
                    sb.AppendLine($"                if (Enum.TryParse<{prop.PropertyTypeName}>(enumStr_{prop.PropertyName}, true, out var enumVal_{prop.PropertyName}))");
                    sb.AppendLine($"                    val_{prop.PropertyName} = enumVal_{prop.PropertyName};");
                    break;
                case PropertyKind.NullableEnum:
                    sb.AppendLine($"                var enumStr_{prop.PropertyName} = dr.AsToString(ords.{prop.PropertyName}Ordinal);");
                    string underlyingType = prop.PropertyTypeName.TrimEnd('?');
                    sb.AppendLine($"                if (!string.IsNullOrWhiteSpace(enumStr_{prop.PropertyName}) && Enum.TryParse<{underlyingType}>(enumStr_{prop.PropertyName}, true, out var enumVal_{prop.PropertyName}))");
                    sb.AppendLine($"                    val_{prop.PropertyName} = enumVal_{prop.PropertyName};");
                    sb.AppendLine("                else");
                    sb.AppendLine($"                    val_{prop.PropertyName} = null;");
                    break;
                case PropertyKind.CustomConverter:
                    sb.AppendLine($"                val_{prop.PropertyName} = ({prop.PropertyTypeName})_converter_{prop.PropertyName}.GetData(dr, ords.{prop.PropertyName}Ordinal)!;");
                    break;
                default:
                    sb.AppendLine($"                val_{prop.PropertyName} = ({prop.PropertyTypeName})_converter_{prop.PropertyName}.Value.GetData(dr, ords.{prop.PropertyName}Ordinal)!;");
                    break;
            }

            sb.AppendLine("            }");
        }

        private static void EmitDataRowPropertyAssignment(StringBuilder sb, PropertyToGenerate prop)
        {
            if (prop.Kind == PropertyKind.String && !prop.PropertyTypeName.EndsWith("?"))
            {
                sb.AppendLine($"            {prop.PropertyTypeName} val_{prop.PropertyName} = string.Empty;");
            }
            else
            {
                sb.AppendLine($"            {prop.PropertyTypeName} val_{prop.PropertyName} = default!;");
            }

            sb.AppendLine($"            if (ords.{prop.PropertyName}Ordinal >= 0)");
            sb.AppendLine("            {");

            switch (prop.Kind)
            {
                case PropertyKind.String:
                    if (prop.PropertyTypeName.EndsWith("?"))
                    {
                        sb.AppendLine($"                val_{prop.PropertyName} = dr.AsString(ords.{prop.PropertyName}Ordinal);");
                    }
                    else
                    {
                        sb.AppendLine($"                val_{prop.PropertyName} = dr.AsString(ords.{prop.PropertyName}Ordinal) ?? string.Empty;");
                    }
                    break;
                case PropertyKind.Int32:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsInt(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableInt32:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullInt(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Int64:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsLong(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableInt64:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullLong(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Int16:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsShort(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableInt16:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullShort(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Byte:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsByte(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableByte:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullByte(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.SByte:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsSByte(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableSByte:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullSByte(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.UInt32:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsUInt(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableUInt32:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullUInt(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.UInt64:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsULong(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableUInt64:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullULong(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.UInt16:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsUShort(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableUInt16:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullUShort(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Boolean:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsBool(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableBoolean:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullBool(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.DateTime:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsDateTime(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableDateTime:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullDateTime(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.DateTimeOffset:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsDateTimeOffset(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableDateTimeOffset:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullDateTimeOffset(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Guid:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsGuid(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableGuid:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullGuid(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Decimal:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsDecimal(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableDecimal:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullDecimal(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Double:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsDouble(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableDouble:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullDouble(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.Single:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsFloat(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.NullableSingle:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullFloat(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.ByteArray:
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsBinary(ords.{prop.PropertyName}Ordinal);");
                    break;
                case PropertyKind.DateOnly:
                    sb.AppendLine("#if NET6_0_OR_GREATER");
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsDateOnly(ords.{prop.PropertyName}Ordinal);");
                    sb.AppendLine("#endif");
                    break;
                case PropertyKind.NullableDateOnly:
                    sb.AppendLine("#if NET6_0_OR_GREATER");
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullDateOnly(ords.{prop.PropertyName}Ordinal);");
                    sb.AppendLine("#endif");
                    break;
                case PropertyKind.TimeOnly:
                    sb.AppendLine("#if NET6_0_OR_GREATER");
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsTimeOnly(ords.{prop.PropertyName}Ordinal);");
                    sb.AppendLine("#endif");
                    break;
                case PropertyKind.NullableTimeOnly:
                    sb.AppendLine("#if NET6_0_OR_GREATER");
                    sb.AppendLine($"                val_{prop.PropertyName} = dr.AsNullTimeOnly(ords.{prop.PropertyName}Ordinal);");
                    sb.AppendLine("#endif");
                    break;
                case PropertyKind.Enum:
                    sb.AppendLine($"                var enumStr_{prop.PropertyName} = dr.AsToString(ords.{prop.PropertyName}Ordinal);");
                    sb.AppendLine($"                if (Enum.TryParse<{prop.PropertyTypeName}>(enumStr_{prop.PropertyName}, true, out var enumVal_{prop.PropertyName}))");
                    sb.AppendLine($"                    val_{prop.PropertyName} = enumVal_{prop.PropertyName};");
                    break;
                case PropertyKind.NullableEnum:
                    sb.AppendLine($"                var enumStr_{prop.PropertyName} = dr.AsToString(ords.{prop.PropertyName}Ordinal);");
                    string underlyingType = prop.PropertyTypeName.TrimEnd('?');
                    sb.AppendLine($"                if (!string.IsNullOrWhiteSpace(enumStr_{prop.PropertyName}) && Enum.TryParse<{underlyingType}>(enumStr_{prop.PropertyName}, true, out var enumVal_{prop.PropertyName}))");
                    sb.AppendLine($"                    val_{prop.PropertyName} = enumVal_{prop.PropertyName};");
                    sb.AppendLine("                else");
                    sb.AppendLine($"                    val_{prop.PropertyName} = null;");
                    break;
                case PropertyKind.CustomConverter:
                    sb.AppendLine($"                val_{prop.PropertyName} = ({prop.PropertyTypeName})_converter_{prop.PropertyName}.GetData(dr, ords.{prop.PropertyName}Ordinal)!;");
                    break;
                default:
                    sb.AppendLine($"                val_{prop.PropertyName} = ({prop.PropertyTypeName})_converter_{prop.PropertyName}.Value.GetData(dr, ords.{prop.PropertyName}Ordinal)!;");
                    break;
            }

            sb.AppendLine("            }");
        }
    }
}
