<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <RootNamespace>CA.Blocks.PostgresDataAccessTests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>false</IsTestProject>
    <!-- Forces MTP to automatically output a TRX report every run -->
    <TestingPlatformCommandLineArguments>--report-trx</TestingPlatformCommandLineArguments>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" Version="13.4.6" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.9.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CA.Blocks.DataAccess.Extensions.Translators.Json\CA.Blocks.DataAccess.Extensions.Translators.Json.csproj" />
    <ProjectReference Include="..\CA.Blocks.DataAccess.Extensions.Translators.NUlid\CA.Blocks.DataAccess.Extensions.Translators.NUlid.csproj" />
    <ProjectReference Include="..\CA.Blocks.PostgresAppHost\CA.Blocks.PostgresAppHost.csproj" />
    <ProjectReference Include="..\CA.Blocks.PostgresDataAccess\CA.Blocks.PostgresDataAccess.csproj" />
  </ItemGroup>

</Project>
