<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyVersion>987.654.3210.0</AssemblyVersion>
    <FileVersion>987.654.3210.0</FileVersion>
    <Version>987.654.3210</Version>
    <Authors>Kevin Bosch</Authors>
    <Company>Ravin Enterprises Limited</Company>
    <RepositoryUrl></RepositoryUrl>
    <AssemblyName>CA.Blocks.DataAccess.Model</AssemblyName>
    <RootNamespace>CA.Blocks.DataAccess.Model</RootNamespace>
    <PackageId>CA.Blocks.DataAccess.Model</PackageId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>C:\GitHub\CA.Blocks.DataAccess\CA.Blocks.DataAccess.Model\CA.Blocks.DataAccess.Model.xml</DocumentationFile>
  </PropertyGroup>

</Project>

