<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <AssemblyVersion>987.654.3210.0</AssemblyVersion>
	  <FileVersion>987.654.3210.0</FileVersion>
	  <Version>987.654.3210</Version>
	  <RepositoryUrl>https://dev.azure.com/RavinEnterprises/CA.Blocks/_git/CA.Blocks.DataAccess</RepositoryUrl>
	  <AssemblyName>CA.Blocks.MySQLDataAccess</AssemblyName>
	  <RootNamespace>CA.Blocks.MySQLDataAccess</RootNamespace>
	  <Authors>Kevin Bosch</Authors>
	  <Company>Ravin Enterprises Limited</Company>
	  <Title>CA.Blocks.MySQLDataAccess</Title>
	  <RepositoryType>git</RepositoryType>
	  <PackageProjectUrl>https://www.codeassociate.com/Blocks/DataAccess/</PackageProjectUrl>
	  <PackageReadmeFile>readme.md</PackageReadmeFile>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <PackageReleaseNotes>@RELEASE-NOTES.txt</PackageReleaseNotes>
	  <PackageTags>data;micro-orm;sql;ca.blocks;ado.net;mysql</PackageTags>
	  <IncludeSymbols>True</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>C:\GitHub\CA.Blocks.DataAccess\CA.Blocks.MySQLDataAccess\CA.Blocks.MySQLDataAccess.xml</DocumentationFile>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CA.Blocks.DataAccess.Model\CA.Blocks.DataAccess.Model.csproj" />
    <ProjectReference Include="..\CA.Blocks.DataAccess\CA.Blocks.DataAccess.csproj" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="10.0.300" PrivateAssets="All" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\CA.Blocks.MySQLDataAccess\readme.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
