<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

	  <TargetFrameworks>netstandard2.0;net6.0;net8.0</TargetFrameworks>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <AssemblyVersion>987.654.3210.0</AssemblyVersion>
	  <FileVersion>987.654.3210.0</FileVersion>
	  <Version>987.654.3210</Version>
	  <RepositoryUrl>https://dev.azure.com/RavinEnterprises/CA.Blocks/_git/CA.Blocks.DataAccess</RepositoryUrl>
	  <AssemblyName>CA.Blocks.OdbcDataAccess</AssemblyName>
	  <RootNamespace>CA.Blocks.OdbcDataAccess</RootNamespace>
	  <Authors>Kevin Bosch</Authors>
	  <Company>Ravin Enterprises Limited</Company>
	  <Title>CA.Blocks.OdbcDataAccess</Title>
	  <RepositoryType>git</RepositoryType>
	  <PackageProjectUrl>https://www.codeassociate.com/Blocks/DataAccess/</PackageProjectUrl>
	  <PackageReadmeFile>readme.md</PackageReadmeFile>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageReleaseNotes>@RELEASE-NOTES.txt</PackageReleaseNotes>
	  <PackageTags>data;micro-orm;sql;ca.blocks;ado.net;odbc</PackageTags>
	  <IncludeSymbols>True</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.Odbc" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CA.Blocks.DataAccess\CA.Blocks.DataAccess.csproj" />
  </ItemGroup>

	<ItemGroup>
		<None Include="..\CA.Blocks.OdbcDataAccess\readme.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
